spring.application.name=messaging-service
server.port=8082
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/msg
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=rg.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true