spring.application.name=api-gateway
server.port=8762

#this property is  by default fetch by spring boot if not added,
# Note: port no. should be 8761 for eureka/discovery-server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# this is old version
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#new version as we are using webflux , version 2025
# there are two types gateway webflux and webMVC
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
